language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
    - TOX_ENV=pep8
    - TOX_ENV=docs
install:
    - pip install tox python-coveralls d2to1 --use-mirrors --download-cache $HOME/.pip-cache
cache:
    directories:
        - $HOME/.pip-cache/
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls
